version: '3.5'
services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    hostname: zookeeper
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.10
  clickhouse01:
    image: clickhouse/clickhouse-server:22.8.4.7
    container_name: clickhouse01
    hostname: clickhouse01
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.11
    ports:
      - "18123:8123"
      - "19000:9000"
    volumes:
      - /clickhousedb-data/clickhouse01:/etc/clickhouse-server
    ulimits:
        nofile:
            soft: 262144
            hard: 262144
    depends_on:
      - zookeeper
  clickhouse02:
    image: clickhouse/clickhouse-server:22.8.4.7
    container_name: clickhouse02
    hostname: clickhouse02
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.12
    ports:
      - "28123:8123"
      - "29000:9000"
    volumes:
      - /clickhousedb-data/clickhouse02:/etc/clickhouse-server
    ulimits:
        nofile:
            soft: 262144
            hard: 262144
    depends_on:
      - zookeeper
  clickhouse03:
    image: clickhouse/clickhouse-server:22.8.4.7
    container_name: clickhouse03
    hostname: clickhouse03
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.13
    ports:
      - "38123:8123"
      - "39000:9000"
    volumes:
      - /clickhousedb-data/clickhouse03:/etc/clickhouse-server
    ulimits:
        nofile:
            soft: 262144
            hard: 262144
    depends_on:
      - zookeeper
  clickhouse04:
    image: clickhouse/clickhouse-server:22.8.4.7
    container_name: clickhouse04
    hostname: clickhouse04
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.14
    ports:
      - "48123:8123"
      - "49000:9000"
    volumes:
      - /clickhousedb-data/clickhouse04:/etc/clickhouse-server
    ulimits:
        nofile:
            soft: 262144
            hard: 262144
    depends_on:
      - zookeeper

networks:
  clickhouse-network:
    name: clickhouse-network
    ipam:
      config:
        - subnet: 172.23.0.0/24
