version: '3.5'
services:
  zookeeper1:
    image: zookeeper:3.7
    container_name: zookeeper1
    hostname: zookeeper1
    env_file:
      - zookeeper1.env
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.8
    volumes:
      - /clickhousedb-data/zookeeper01/dataDir:/data
      - /clickhousedb-data/zookeeper01/dataLogDir:/datalog
      - /clickhousedb-data/zookeeper01/logs:/logs
  zookeeper2:
    image: zookeeper:3.7
    container_name: zookeeper2
    hostname: zookeeper2
    env_file:
      - zookeeper2.env
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.9
    volumes:
      - /clickhousedb-data/zookeeper02/dataDir:/data
      - /clickhousedb-data/zookeeper02/dataLogDir:/datalog
      - /clickhousedb-data/zookeeper02/logs:/logs
  zookeeper3:
    image: zookeeper:3.7
    container_name: zookeeper3
    hostname: zookeeper3
    env_file:
      - zookeeper3.env
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.10
    volumes:
      - /clickhousedb-data/zookeeper03/dataDir:/data
      - /clickhousedb-data/zookeeper03/dataLogDir:/datalog
      - /clickhousedb-data/zookeeper03/logs:/logs
  clickhouse01:
    image: clickhouse/clickhouse-server:22.8.4.7
    container_name: clickhouse01
    hostname: clickhouse01
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.11
    ports:
      - "18123:8123"
      - "19000:9000"
    volumes:
      - /clickhousedb-data/clickhouse01/config:/etc/clickhouse-server
      - /clickhousedb-data/clickhouse01/dataDir:/var/lib/clickhouse
    ulimits:
        nofile:
            soft: 262144
            hard: 262144
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
  clickhouse02:
    image: clickhouse/clickhouse-server:22.8.4.7
    container_name: clickhouse02
    hostname: clickhouse02
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.12
    ports:
      - "28123:8123"
      - "29000:9000"
    volumes:
      - /clickhousedb-data/clickhouse02/config:/etc/clickhouse-server
      - /clickhousedb-data/clickhouse02/dataDir:/var/lib/clickhouse
    ulimits:
        nofile:
            soft: 262144
            hard: 262144
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
  clickhouse03:
    image: clickhouse/clickhouse-server:22.8.4.7
    container_name: clickhouse03
    hostname: clickhouse03
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.13
    ports:
      - "38123:8123"
      - "39000:9000"
    volumes:
      - /clickhousedb-data/clickhouse03/config:/etc/clickhouse-server
      - /clickhousedb-data/clickhouse03/dataDir:/var/lib/clickhouse
    ulimits:
        nofile:
            soft: 262144
            hard: 262144
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
  clickhouse04:
    image: clickhouse/clickhouse-server:22.8.4.7
    container_name: clickhouse04
    hostname: clickhouse04
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.14
    ports:
      - "48123:8123"
      - "49000:9000"
    volumes:
      - /clickhousedb-data/clickhouse04/config:/etc/clickhouse-server
      - /clickhousedb-data/clickhouse04/dataDir:/var/lib/clickhouse
    ulimits:
        nofile:
            soft: 262144
            hard: 262144
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

networks:
  clickhouse-network:
    name: clickhouse-network
    ipam:
      config:
        - subnet: 172.23.0.0/24
